version: "3.9"

services:
  # The Agent Service
  agent-service:
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: agent_service_c
    # Internal only now (exposed through nginx reverse proxy for HTTPS)
    env_file:
      - .env
    depends_on:
      - tool-server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    networks:
      - chatbot-net
    restart: always

  # The Tool Server
  tool-server:
    build:
      context: .
      dockerfile: tool.Dockerfile
    container_name: tool_server_c
    # Internal only now (exposed through nginx reverse proxy for HTTPS)
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    networks:
      - chatbot-net
    restart: always

  # Nginx reverse proxy (internal only - accessed via host nginx at /chatbot)
  nginx:
    image: nginx:1.27-alpine
    container_name: chatbot_nginx
    depends_on:
      - agent-service
      - tool-server
    ports:
      # Internal access only - host nginx will proxy to this
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - chatbot-net
    restart: unless-stopped

networks:
  chatbot-net:
    driver: bridge
