version: "3.9"

services:
  # The Agent Service
  agent-service:
    build:
      context: .
      dockerfile: agent.Dockerfile
    container_name: agent_service_c
    # Internal only now (exposed through nginx reverse proxy for HTTPS)
    env_file:
      - .env
    depends_on:
      - tool-server
    networks:
      - chatbot-net

  # The Tool Server
  tool-server:
    build:
      context: .
      dockerfile: tool.Dockerfile
    container_name: tool_server_c
    env_file:
      - .env
    networks:
      - chatbot-net

  # Nginx reverse proxy providing HTTPS termination
  nginx:
    image: nginx:1.27-alpine
    container_name: chatbot_nginx
    depends_on:
      - agent-service
      - tool-server
    ports:
      # Remapped to avoid host conflicts: access via https://localhost:8443
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/cert.pem:/etc/ssl/certs/server.crt:ro
      - ./ssl/key.pem:/etc/ssl/private/server.key:ro
    networks:
      - chatbot-net
    restart: unless-stopped

networks:
  chatbot-net:
    driver: bridge